version: '3'

services:
  database:
    container_name: 'tcc_produtos_container'
    image: 'postgres:13-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tcc_produtos
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
